  name: pipeline
 
on:
  push:
  workflow_dispatch:
 
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: mvn test
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.11.0
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
 
  build:
    runs-on: ubuntu-latest
    needs: unit-test  # Recomendado para garantir ordem
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: target/
      - name: Upload JAR
        uses: actions/upload-artifact@v4.4.0
        with:
          name: artifact
          path: ./target/demo-0.0.2.7-SNAPSHOT.jar
      - name: Package
        run: mvn package
        
